sylver35_breizhcharts_page_music:
    path: /breizhcharts/{mode}/{cat}
    defaults: { _controller: sylver35.breizhcharts.controller.breizhcharts:handle }
    requirements:
        mode: \w+
        cat: \d+

sylver35_breizhcharts_page_user:
    path: /breizhcharts/other/{userid}/{cat}/{name}
    defaults: { _controller: sylver35.breizhcharts.controller.breizhcharts:handle_user }
    requirements:
        userid: \d+
        cat: \d+

sylver35_breizhcharts_video:
    path: /breizhcharts/video/{id}/{song_name}
    defaults: { _controller: sylver35.breizhcharts.controller.breizhcharts:handle_video }
    requirements:
        id: \d+

sylver35_breizhcharts_song_view:
    path: /breizhcharts_song_view/{id}
    defaults: { _controller: sylver35.breizhcharts.controller.breizhcharts:song_view }
    requirements:
        id: \d+

sylver35_breizhcharts_result:
    path: /breizhcharts/list_results
    defaults: { _controller: sylver35.breizhcharts.controller.breizhcharts:get_result }

sylver35_breizhcharts_add_video:
    path: /breizhcharts/add_video
    defaults: { _controller: sylver35.breizhcharts.controller.breizhcharts:handle_add }

sylver35_breizhcharts_check_video:
    path: /breizhcharts_check_video/{check}/{song_id}
    defaults: { _controller: sylver35.breizhcharts.controller.breizhcharts:check_youtube_video }
    requirements:
        check: \d+
        song_id: \d+

sylver35_breizhcharts_delete_music:
    path: /breizhcharts_del/delete/{id}
    defaults: { _controller: sylver35.breizhcharts.controller.breizhcharts:delete_song }
    requirements:
        id: \d+

sylver35_breizhcharts_edit_video:
    path: /breizhcharts/edit/{id}/{start}/{cat}
    defaults: { _controller: sylver35.breizhcharts.controller.breizhcharts:handle_edit }
    requirements:
        id: \d+
        start: \d+
        cat: \d+

sylver35_breizhcharts_page_popup:
    path: /breizhcharts_popup/{id}
    defaults: { _controller: sylver35.breizhcharts.controller.breizhcharts:display_popup }
    requirements:
        id: \d+

sylver35_breizhcharts_vote:
    path: /breizhcharts_vote
    defaults: { _controller: sylver35.breizhcharts.controller.breizhcharts:handle_vote  }

sylver35_breizhcharts_check_song:
    path: /breizhcharts_check_song
    defaults: { _controller: sylver35.breizhcharts.controller.breizhcharts:check_song  }

sylver35_breizhcharts_report_video:
    path: /breizhcharts/report/video/{id}
    defaults: { _controller: sylver35.breizhcharts.report.controller:report_video  }
    requirements:
        id: \d+

sylver35_breizhcharts_report_validate:
    path: /breizhcharts/report/validate/{id}
    defaults: { _controller: sylver35.breizhcharts.report.controller:report_validate  }
    requirements:
        id: \d+

sylver35_breizhcharts_reported_video:
    path: /breizhcharts/report/viewreport/{id}
    defaults: { _controller: sylver35.breizhcharts.report.controller:view_report  }
    requirements:
        id: \d+

sylver35_breizhcharts_list_report:
    path: /breizhcharts/report/list
    defaults: { _controller: sylver35.breizhcharts.report.list:display_list  }

sylver35_breizhcharts_tools:
    path: /breizhcharts/tools/{mode}
    defaults: { _controller: sylver35.breizhcharts.core.tools:display_tools  }
    requirements:
        mode: \w+

sylver35_breizhcharts_ajax_cats:
    path: /breizhcharts/ajax
    defaults: { _controller: sylver35.breizhcharts.admin.categories:ajax_cats  }
