parameters:
    sylver35.breizhcharts.table.breizhcharts: '%core.table_prefix%breizhcharts'
    sylver35.breizhcharts.table.breizhcharts_cats: '%core.table_prefix%breizhcharts_cats'
    sylver35.breizhcharts.table.breizhcharts_result: '%core.table_prefix%breizhcharts_result'
    sylver35.breizhcharts.table.breizhcharts_voters: '%core.table_prefix%breizhcharts_voters'

    _defaults:
        public: true